### PR TITLE
fix issue #7

### PR DESCRIPTION
**Pull request by NiiVx**

### CODE REVIEW

**Comment by NiiVx** [comment]
I decided to change the functions but I saw that removing React.StricMode also works but I was afraid that this way it would affect the rest of the code beyond home

**Comment by creative-tutorials** [comment]
> I decided to change the functions but I saw that removing React.StricMode also works but I was afraid that this way it would affect the rest of the code beyond home

Okay thanks, so you only replaced useState with useRef

**Comment by NiiVx** [comment]
Yes, also remove the else statement because now the logic is inside the useEffect

**Comment by NiiVx** [comment]
> 
> 
> 
> 
> > I decided to change the functions but I saw that removing React.StricMode also works but I was afraid that this way it would affect the rest of the code beyond home
> 
> Okay thanks, so you only replaced useState with useRef

Yes, also remove the else statement because now the logic is inside the useEffect

**Comment by creative-tutorials** [comment]
> > > I decided to change the functions but I saw that removing React.StricMode also works but I was afraid that this way it would affect the rest of the code beyond home
> > 
> > 
> > Okay thanks, so you only replaced useState with useRef
> 
> Yes, also remove the else statement because now the logic is inside the useEffect

Okay Thanks for the help 🙂

**Comment by NiiVx** [comment]
> > > > I decided to change the functions but I saw that removing React.StricMode also works but I was afraid that this way it would affect the rest of the code beyond home
> > > 
> > > 
> > > Okay thanks, so you only replaced useState with useRef
> > 
> > Yes, also remove the else statement because now the logic is inside the useEffect
> 
> Okay Thanks for the help 🙂

Anytime! Can you put the label HACKTOBERFEST-ACCEPTED ? I will really appreciate it!

**Comment by creative-tutorials** [comment]
> > > > > I decided to change the functions but I saw that removing React.StricMode also works but I was afraid that this way it would affect the rest of the code beyond home
> > > > 
> > > > 
> > > > Okay thanks, so you only replaced useState with useRef
> > > 
> > > 
> > > Yes, also remove the else statement because now the logic is inside the useEffect
> > 
> > 
> > Okay Thanks for the help 🙂
> 
> Anytime! Can you put the label HACKTOBERFEST-ACCEPTED ? I will really appreciate it!

What do you mean?

**Comment by creative-tutorials** [comment]
> oh sorry I was thinking it was a necessary thing to the event but automatically after the merge I received a message by them. Anyway, thanks man!

You're welcome anytime 😉 Your contributions or welcome anytime also. ☕

**Pull request merged**
